version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    image: php:7.4-apache
    build:
      context: ./html
      dockerfile: Dockerfile
    depends_on:
      - db
    #volumes:
    #  - ./html:/var/www/html/
    ports:
      - 8000:80
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: administratorPassword!!!
        MYSQL_DATABASE: webapp
        MYSQL_USER: admin
        MYSQL_PASSWORD: administratorPassword!!!
    ports:
        - "9906:3306"
    volumes:
        - ./html/resources/script.sql:/docker-entrypoint-initdb.d/1.sql

  phpmyadmin:
    image: phpmyadmin
    ports:
        - '8080:80'
    restart: always
    environment:
        PMA_HOST: db
    depends_on:
        - db
